### ISSUE TITLE
writing TODO before submitting

### ISSUE THREAD

**Issue by dengemann** [meeg-ml-benchmarks/brain-age-benchmark-paper#41]
Here is a small progress tracker, mostly focusing on the manuscript text (all this must happen by end of Tuesday 30th of November; I will then send what we have by then to Roche's internal communications reviewers)

- [x] update main figures and table after changes from #43 and #44
- [ ] take into account open suggestions / comments by Tonio on wording
- [x] software section: list all packages, perhaps highlight the ones that are partly our contributions
- [x] conclusion
- [x] research ideas
- [x] Author contributions  
- [x] Acknowledgment section: Cuba and Leipzig and TUAB
- [x] write discussion, focus on outline indicated in text
- [x] complete / write methods section on validation / scoring strategy
- [x] spell out details / rationale of hand-crafted features + add citations
- [x] complete main text in results section, focus on dividing the labor nicely between the captions and main text
- [x] write abstract
- [x] integrate data flow table in main text
- [x] make results table
