### ISSUE TITLE
Code TODO before submitting

### ISSUE THREAD

**Issue by dengemann** [meeg-ml-benchmarks/brain-age-benchmark-paper#45]
This is not a list of what'd be nice to have but what's crucial for the reviewers to do inspect our code / software contribuion.
We should make sure all points are addressed within till next Monday.

- [x] write read me with clear instructions on how to use the repo
- [x] release caffeine
- [x] release (?) mine-bids-pipeline
- [x] release mne-features
- [x] release braindecode ?
- [ ] refactor some of the code (put functions from scripts into utils.py / library

What else? @agramfort @gemeinl @hubertjb @apmellot ...
